CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL UNIQUE, role ENUM('user', 'admin') DEFAULT 'user', phone VARCHAR(20) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_reports (
    report_id INT AUTO_INCREMENT PRIMARY KEY, sender INT NOT NULL, complaint TEXT NOT NULL, receiver INT NOT NULL, report_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);